#
# Module manifest for module 'InitializeDevMachine'
#
# Generated by: Prajeesh Prathap
#
# Generated on: 07/20/2016
#
@{
    ModuleVersion = '1.0'
    GUID = 'DEF66DBA-0611-4041-A13C-489AE68BB0EC'
    Author = 'Prajeesh Prathap'
    CompanyName = 'Info support'
    Copyright = '(c) 2016 Info support. All rights reserved.'
    RootModule = 'InitializeDevMachine.schema.psm1'
}
